#!/bin/bash
IFS=$'\n'
INPUTS=( "${@:-"-"}" )
for i in "${INPUTS[@]}"; do
	if [[ "$i" != "-" ]]; then
		exec 3< "$i" || exit 1
	else
		exec 3<&0
	fi

	while read -ru 3 line; do
		echo -E "$line"
	done
done
exec 3>&-
